// Generated by https://quicktype.io

export interface IMap {
  width: number;
  height: number;
  slug: string;
  islands: IIsland[];
}

export interface IIsland {
  map: Array<number[]>;
  start: number[];
}

// Generated by https://quicktype.io

export interface IScanResponse {
  success: boolean;
  scan: IScan;
}

export interface IScan {
  myShips: IMyShip[];
  enemyShips: any[];
  zone: null;
  tick: number;
}

export interface IMyShip {
  id: number;
  x: number;
  y: number;
  size: number;
  hp: number;
  maxHp: number;
  direction: "north" | "east" | "south" | "west";
  speed: number;
  maxSpeed: number;
  minSpeed: number;
  maxChangeSpeed: number;
  cannonCooldown: number;
  cannonCooldownLeft: number;
  cannonRadius: number;
  scanRadius: number;
  cannonShootSuccessCount: number;
}

export enum IDirection {
  North = "north",
  East = "east",
  South = "south",
  West = "west",
}
